---
galaxy_info:
  author: Jan Christian Gr√ºnhage <jan.christian@gruenhage.xyz>
  description: Install and configure yggdrasil

  license: AGPLv3

  min_ansible_version: 2.5

  platforms:
    - name: Void Linux
      versions:
        - any
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - sid
    - name: Fedora    # Depends on redhat-lsb-core
      versions:
        - 28
        - 29
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - cosmic
    - name: ArchLinux # Depends on python and lsb-release and some aur tool
      versions:
        - any

  galaxy_tags: []

dependencies: []
